name: Docker Push

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "computer-vision/Dockerfile"
          IMAGE_NAME: "paperplanes/kubeflow-jupyter"
          TAG_NAME: "cv-latest"
          LATEST: "false"
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "computer-vision/Dockerfile"
          IMAGE_NAME: "paperplanes/kubeflow-jupyter"
          TAG_NAME: cv-latest-${{ steps.vars.outputs.sha_short }}
          LATEST: "false"
